# Generated by Django 2.1.5 on 2019-11-01 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CosmeticsModel',
            fields=[
                ('c_no', models.IntegerField(primary_key=True, serialize=False)),
                ('c_name', models.CharField(max_length=100)),
                ('c_price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CosmeticsTypeModel',
            fields=[
                ('c_typeno', models.IntegerField(primary_key=True, serialize=False)),
                ('c_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='cosmeticsmodel',
            name='c_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cosmetics.CosmeticsTypeModel'),
        ),
    ]
